### ISSUE TITLE
Cannot export image, exception java.lang.StringIndexOutOfBoundsException: String index out of range: -1

### ISSUE THREAD

**Issue by nghinv** [Ant-Grand/GrandUI#18]
Hello,
I am using grand-ui v.0.8.6 in ubuntu. The grand started by command line: ./grand-ui-0.8.6/grand-ui

The ant script visualization works well, but while I cannot export image using "Export Graph as an image".
Exception in the console:
{code}
`Dec 05, 2019 4:05:20 PM net.ggtools.grand.ant.LinkFinderVisitor info
INFO: Processing antcall target in doPackageAddonsWarFile
Dec 05, 2019 4:05:20 PM net.ggtools.grand.ant.LinkFinderVisitor info
INFO: Processing antcall target in doEbxAddonsPackageUpdate
Dec 05, 2019 4:05:20 PM net.ggtools.grand.ant.LinkFinderVisitor info
INFO: Processing antcall target in doEbxAddonsPackageUpdate
Dec 05, 2019 4:05:20 PM net.ggtools.grand.ant.LinkFinderVisitor info
INFO: Processing antcall target in doEbxAddonsPackageUpdate
Dec 05, 2019 4:05:20 PM net.ggtools.grand.ant.LinkFinderVisitor info
INFO: Processing antcall target in doEbxAddonsPackageUpdate
Dec 05, 2019 4:05:20 PM net.ggtools.grand.ant.LinkFinderVisitor info
INFO: Processing antcall target in confirmDownloadLGPLFromTibco
Dec 05, 2019 4:05:20 PM net.ggtools.grand.ant.LinkFinderVisitor info
INFO: Processing antcall target in confirmDownloadLGPLFromTibco
Dec 05, 2019 4:05:20 PM net.ggtools.grand.ant.LinkFinderVisitor info
INFO: Processing antcall target in doRepackageTestsWAR
Dec 05, 2019 4:05:21 PM net.ggtools.grand.ui.graph.GraphController info
INFO: Opening graph displayer
Dec 05, 2019 4:05:21 PM net.ggtools.grand.ui.graph.GraphController info
INFO: Graph loaded & rendered
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1927)
	at org.eclipse.swt.widgets.FileDialog.presetChooserDialog(FileDialog.java:437)
	at org.eclipse.swt.widgets.FileDialog.openChooserDialog(FileDialog.java:339)
	at org.eclipse.swt.widgets.FileDialog.open(FileDialog.java:305)
	at net.ggtools.grand.ui.actions.ExportGraphAction.run(ExportGraphAction.java:92)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:476)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:568)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:400)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5797)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1374)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5051)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4583)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:821)
	at org.eclipse.jface.window.Window.open(Window.java:797)
	at net.ggtools.grand.ui.Application.run(Application.java:364)
	at net.ggtools.grand.ui.Application.main(Application.java:162)
`
{code}

Could you please give me some advice?

thanks,
Nghi

**Comment by nghinv** [comment]
Java version:
`java version "1.8.0_221"
Java(TM) SE Runtime Environment (build 1.8.0_221-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.221-b11, mixed mode)
`

**Comment by twogee** [comment]
Hello Nghi,

by the looks of it, there is a problem with interaction between SWT and GTK.

In the history of [FileDialog](https://github.com/eclipse/eclipse.platform.swt/commits/master/bundles/org.eclipse.swt/Eclipse%20SWT/gtk/org/eclipse/swt/widgets/FileDialog.java) I see recent changes related to switch from GTK 2 to 3 (which add about 50 lines of code, so the exception happens in a different place in `presetChooserDialog()`, if you try to compare with the latest version of code) just after the Eclipse 4.9 release which is used by GrandUI. The problem seems to happen here
```
				int separatorIndex = extFilter.lastIndexOf (FILE_EXTENSION_SEPARATOR);
				String extension = extFilter.substring (separatorIndex);
```
where extFilter is extracted from a string returned by a call to GTK.

A corresponding change of GTK in JDK is JEP 283, [backported](https://bugs.openjdk.java.net/browse/JDK-8207322) to Java 8 and released by Oracle as u231. I am not sure if OpenJDK follows Oracle feature by feature. Could you please check which versions of GTK are available in your Ubuntu setup?  I will investigate the issue more throughly during the weekend and having that bit of knowledge available would surely help.

**Comment by nghinv** [comment]
Hi,
The problem still persists on java 1.8.0_231-b11

`java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1927)
	at org.eclipse.swt.widgets.FileDialog.presetChooserDialog(FileDialog.java:437)
	at org.eclipse.swt.widgets.FileDialog.openChooserDialog(FileDialog.java:339)
	at org.eclipse.swt.widgets.FileDialog.open(FileDialog.java:305)
	at net.ggtools.grand.ui.actions.ExportGraphAction.run(ExportGraphAction.java:92)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:476)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:568)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:400)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5797)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1374)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5051)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4583)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:821)
	at org.eclipse.jface.window.Window.open(Window.java:797)
	at net.ggtools.grand.ui.Application.run(Application.java:364)
	at net.ggtools.grand.ui.Application.main(Application.java:162)
^C
/tmp$ java -version
java version "1.8.0_231"
Java(TM) SE Runtime Environment (build 1.8.0_231-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.231-b11, mixed mode)
`
Please check!
thanks,
Nghi

**Comment by twogee** [comment]
It is an interplay between JRE, SWT and GTK installed in Ubuntu. Even though the latest Java 8 is supposed to prefer GTK 3, and use `openNativeChooserDialog` rather than `openChooserDialog` when GTK version is higher than or equal to 3.20, it does not happen even though `apt list` says the installed GTK version is 3.22.30; judging by scarcity of bug reports, it looks like a configuration problem. I will try to open an issue with SWT developers and see what is the best solution here.

**Comment by twogee** [comment]
It turns out that ImageSaver was not following the SWT specs 😊 I'll try to release a 0.9 before Christmas.

**Comment by nghinv** [comment]
thanks for your effort!

**Comment by twogee** [comment]
The release is done (#20)

**Comment by nghinv** [comment]
It works for me now.
thanks a lot!
